# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "GCP deploy"
description: "A GitHub Action to deploy to GCP"
author: "anirudhb and Jason Miller (https://github.com/developit) and Firebase"
branding:
  icon: "globe"
  color: "blue"
runs:
  using: "node12"
  main: "bin/action.min.js"
inputs:
  repoToken:
    description: "The GITHUB_TOKEN secret"
    required: false
  urls:
    required: true
    description: The url(s) deployed to, comma separated
  expire_time:
    required: true
    description: When preview URLs expire
  details_url:
    required: true
    description: A single deployed URL
  failure:
    required: false
    description: Whether the deployment failed
  error_message:
    required: false
    description: The error message
outputs:
  urls:
    description: The url(s) deployed to
  expire_time:
    description: The time the deployed preview urls expire
  details_url:
    description: A single URL that was deployed to
